// @ts-check
const navigation = Object.freeze([
  Object.freeze({ label: 'Servicios', href: '#servicios' }),
  Object.freeze({ label: 'Entregables', href: '#entregables' }),
  Object.freeze({ label: 'Proceso', href: '#proceso' }),
  Object.freeze({ label: 'Experiencia', href: '#experiencia' }),
  Object.freeze({ label: 'Preguntas frecuentes', href: '#preguntas-frecuentes' }),
  Object.freeze({ label: 'Contacto', href: '#contacto' }),
]);

export const siteConfig = Object.freeze({
  brandName: 'Jato Labs',
  founderName: 'Miguel Jato',
  domain: 'https://jatolabs.tech',
  email: 'hola@jatolabs.tech',
  location: 'México / Remoto',
  linkedinUrl: 'https://www.linkedin.com/in/jatomx/',
  bookingUrl: '',
  bookingSubject: 'Llamada de 30 minutos para mi empresa',
  primaryCta: Object.freeze({ label: 'Agendar llamada de 30 minutos' }),
  navigation,
  audit: Object.freeze({
    hero: Object.freeze({
      title: 'Descubre qué está frenando la escalabilidad de tu negocio',
      subtitle: 'Auditamos procesos, datos y tecnología para identificar qué aporta valor, eliminar fricción y convertir hallazgos en un roadmap priorizado de 90 días.',
      secondaryCta: 'Ver entregables',
      reassurance: 'Sin compromiso. No necesitas preparar documentación de procesos ni técnica para la primera llamada.',
    }),
    idealClientScenarios: Object.freeze([
      'El equipo compensa procesos frágiles con hojas de cálculo, mensajes o trabajo manual.',
      'Existen esperas, retrabajo, captura duplicada o controles que no reducen riesgos.',
      'Se busca automatizar o incorporar IA sin validar primero el proceso y sus datos.',
      'La plataforma ha crecido sin una revisión integral de procesos y arquitectura.',
      'Los despliegues, incidentes o costos tecnológicos están frenando al negocio.',
      'Se necesita validar procesos y tecnología antes de invertir, migrar o crecer.',
    ]),
    scope: Object.freeze([
      'Mapeo de procesos prioritarios y actividades que aportan valor.',
      'Análisis de fricción, esperas, retrabajo, controles y desperdicio.',
      'Revisión de datos, métricas y oportunidades de automatización.',
      'Diseño del proceso objetivo y criterios de mejora.',
      'Revisión de arquitectura, cloud, seguridad y entrega de software.',
      'Entrevistas con responsables de negocio, operaciones, producto y tecnología.',
    ]),
    duration: 'Duración típica: entre 2 y 4 semanas, dependiendo del alcance y la complejidad de los procesos y sistemas revisados.',
    deliverables: Object.freeze([
      'Resumen ejecutivo.', 'Mapa del proceso actual.', 'Análisis de valor y fricción.',
      'Diseño del proceso objetivo.', 'Scorecard de procesos y tecnología.',
      'Inventario de hallazgos.', 'Matriz de impacto y esfuerzo.',
      'Oportunidades de automatización.', 'Roadmap de 90 días.',
      'Sesión de presentación de resultados.',
    ]),
    scorecard: Object.freeze([
      Object.freeze({ label: 'Procesos', score: '58 / 100', status: 'Alto' }),
      Object.freeze({ label: 'Datos', score: '69 / 100', status: 'Medio' }),
      Object.freeze({ label: 'Arquitectura', score: '72 / 100', status: 'Medio' }),
      Object.freeze({ label: 'Cloud', score: '64 / 100', status: 'Medio' }),
      Object.freeze({ label: 'Seguridad', score: '48 / 100', status: 'Alto' }),
      Object.freeze({ label: 'DevOps', score: '81 / 100', status: 'Bajo' }),
    ]),
    findings: Object.freeze([
      Object.freeze({ title: 'Aprobaciones duplicadas sin reducción de riesgo', area: 'Procesos', severity: 'Alto', impact: 'Mayor tiempo de ciclo y retrabajo', effort: 'Bajo', recommendation: 'Eliminar validaciones redundantes y definir una aprobación basada en criterios medibles.' }),
      Object.freeze({ title: 'Dependencia crítica sin estrategia de recuperación', area: 'Arquitectura', severity: 'Crítico', impact: 'Interrupción prolongada del servicio', effort: 'Alto', recommendation: 'Definir redundancia, respaldos y un plan de recuperación probado.' }),
      Object.freeze({ title: 'Crecimiento de costos cloud sin asignación por servicio', area: 'Cloud', severity: 'Alto', impact: 'Decisiones de costo sin trazabilidad', effort: 'Medio', recommendation: 'Etiquetar recursos y establecer presupuestos por servicio.' }),
      Object.freeze({ title: 'Pipeline de despliegue con validaciones manuales', area: 'DevOps', severity: 'Medio', impact: 'Entregas lentas y propensas a error', effort: 'Bajo', recommendation: 'Automatizar validaciones críticas y criterios de promoción.' }),
      Object.freeze({ title: 'Secretos almacenados fuera de un gestor centralizado', area: 'Seguridad', severity: 'Alto', impact: 'Mayor exposición de credenciales', effort: 'Medio', recommendation: 'Migrar secretos y rotación a un gestor con acceso auditado.' }),
    ]),
    matrix: Object.freeze([
      Object.freeze({ quadrant: 'Alto impacto / bajo esfuerzo', initiative: 'Eliminar aprobaciones duplicadas del proceso' }),
      Object.freeze({ quadrant: 'Alto impacto / alto esfuerzo', initiative: 'Diseñar recuperación de la dependencia crítica' }),
      Object.freeze({ quadrant: 'Bajo impacto / bajo esfuerzo', initiative: 'Normalizar etiquetas de recursos cloud' }),
      Object.freeze({ quadrant: 'Bajo impacto / alto esfuerzo', initiative: 'Reorganizar ambientes no críticos' }),
    ]),
    roadmap: Object.freeze([
      Object.freeze({ period: '0–30 días', items: Object.freeze(['Simplificar el proceso prioritario', 'Definir responsables y métricas']) }),
      Object.freeze({ period: '31–60 días', items: Object.freeze(['Automatizar controles que aportan valor', 'Implementar trazabilidad de costos']) }),
      Object.freeze({ period: '61–90 días', items: Object.freeze(['Probar recuperación y continuidad', 'Revisar avances y ajustar el roadmap']) }),
    ]),
    process: Object.freeze([
      Object.freeze({ title: 'Descubrimiento', description: 'Objetivos, procesos prioritarios, contexto de negocio y riesgos percibidos.', outcome: 'ALINEAR' }),
      Object.freeze({ title: 'Revisión basada en evidencia', description: 'Procesos, datos, arquitectura, repositorios, cloud y entrevistas.', outcome: 'OBSERVAR' }),
      Object.freeze({ title: 'Priorización', description: 'Hallazgos ordenados por impacto, urgencia y esfuerzo.', outcome: 'DECIDIR' }),
      Object.freeze({ title: 'Sesión ejecutiva', description: 'Resultados, decisiones y ruta de acción con tu equipo.', outcome: 'ACTUAR' }),
    ]),
  }),
  expectedOutcomes: Object.freeze([
    'Procesos más simples y medibles.', 'Menos esperas y retrabajo.',
    'Automatización basada en valor.', 'Visibilidad de riesgos, deuda y costos.',
    'Prioridades claras por impacto y esfuerzo.', 'Roadmap alineado con objetivos de negocio.',
  ]),
  technicalProfile: Object.freeze({
    role: 'Technology Executive · CTO · Cloud Architect',
    introduction: 'Miguel Jato combina más de 20 años de experiencia tecnológica con una trayectoria liderando equipos de ingeniería, construyendo plataformas digitales y llevando sistemas críticos desde la arquitectura hasta producción.',
    perspective: 'Su experiencia conecta procesos, profundidad técnica y dirección ejecutiva: cuestiona cómo se crea valor antes de decidir sobre arquitectura, cloud, seguridad o automatización, y conecta esas decisiones con costos, riesgo operativo y crecimiento.',
    highlights: Object.freeze([
      Object.freeze({ value: '20+', label: 'años de experiencia en tecnología' }),
      Object.freeze({ value: 'AWS + GCP', label: 'arquitectura y operación multi-cloud' }),
      Object.freeze({ value: 'CTO', label: 'liderazgo técnico y de ingeniería' }),
    ]),
    expertise: Object.freeze([
      'Arquitectura cloud', 'Plataformas SaaS', 'Modernización tecnológica',
      'Sistemas de misión crítica', 'Liderazgo de ingeniería',
      'Migraciones e integraciones', 'Seguridad y confiabilidad',
      'Rediseño de procesos', 'Ingeniería de software',
    ]),
    credential: Object.freeze({
      name: 'AWS Certified Solutions Architect – Associate',
      issuer: 'Amazon Web Services',
      validity: 'Vigente hasta abril de 2027',
    }),
    linkedinCta: 'Conocer la trayectoria completa en LinkedIn',
  }),
  faqs: Object.freeze([
    Object.freeze({ question: '¿La auditoría empieza por procesos o por tecnología?', answer: 'Empieza por entender el objetivo, el flujo de trabajo y las actividades que aportan valor. Después revisa los datos y la tecnología que habilitan ese proceso. Así se evita automatizar ineficiencias o recomendar herramientas sin una necesidad clara.' }),
    Object.freeze({ question: '¿Necesito compartir el código fuente?', answer: 'No necesariamente desde el inicio. El acceso se acuerda según el alcance; algunas revisiones pueden comenzar con arquitectura, configuración, procesos y entrevistas. Cuando revisar código aporta evidencia relevante, se solicita acceso limitado y explícito.' }),
    Object.freeze({ question: '¿Cómo se protege la información de mi empresa?', answer: 'Antes de compartir información se acuerdan el alcance, los accesos y las medidas de confidencialidad aplicables. Se procura usar accesos mínimos y temporales. Los requisitos contractuales específicos se confirman durante la conversación inicial.' }),
    Object.freeze({ question: '¿La auditoría incluye pruebas de penetración?', answer: 'No se asumen como parte del alcance estándar. La auditoría revisa controles y riesgos técnicos; si se requieren pruebas de penetración, se valida por separado el alcance y la forma adecuada de realizarlas.' }),
    Object.freeze({ question: '¿Trabajan con AWS y Google Cloud?', answer: 'Sí. La experiencia publicada incluye plataformas operadas sobre AWS y Google Cloud. El alcance concreto depende de la arquitectura y los servicios utilizados por tu empresa.' }),
    Object.freeze({ question: '¿Cuánto tiempo debe dedicar mi equipo?', answer: 'Se busca concentrar la participación en entrevistas, habilitación de accesos y validación de hallazgos. La dedicación exacta depende del alcance, la documentación disponible y la complejidad de la plataforma.' }),
    Object.freeze({ question: '¿Pueden ayudar a implementar las recomendaciones?', answer: 'La auditoría incluye el diagnóstico y el diseño del proceso objetivo. La implementación operativa o tecnológica posterior no forma parte automáticamente del alcance y se evalúa y acuerda por separado.' }),
    Object.freeze({ question: '¿La auditoría sirve para procesos de due diligence?', answer: 'Puede aportar evidencia técnica para decisiones de inversión o crecimiento. Los objetivos, profundidad y formato necesarios para un proceso de due diligence deben acordarse específicamente.' }),
    Object.freeze({ question: '¿Cuánto dura la auditoría?', answer: 'La duración típica es de entre 2 y 4 semanas, dependiendo del alcance y la complejidad de los procesos y sistemas revisados.' }),
    Object.freeze({ question: '¿Qué información necesito preparar?', answer: 'No necesitas preparar documentación de procesos ni técnica para la primera llamada. Después se define una lista acotada de flujos, métricas, arquitectura, accesos y personas relevantes según el alcance acordado.' }),
    Object.freeze({ question: '¿Pueden trabajar con mi equipo o proveedor actual?', answer: 'Sí, la revisión está planteada como un proceso colaborativo. La forma de coordinación, responsabilidades y acceso se acuerda con las partes involucradas antes de iniciar.' }),
  ]),
  footer: Object.freeze({
    navigation,
    legal: Object.freeze([]),
  }),
  seo: Object.freeze({ title: 'Jato Labs | Auditoría de procesos y tecnología', description: 'Jato Labs audita y rediseña procesos de negocio apoyados por tecnología para eliminar fricción, priorizar mejoras y orientar decisiones de automatización e inversión.' }),
});
