window.SITE_CONFIG = Object.freeze({
  brandName: 'Jato Labs',
  founderName: 'Miguel Jato',
  domain: 'https://jatolabs.tech',
  email: 'hola@jatolabs.tech',
  location: 'México / Remoto',
  linkedinUrl: 'https://www.linkedin.com/in/jatomx/',
  bookingUrl: '',
  bookingSubject: 'Diagnóstico técnico para mi empresa',
  audit: Object.freeze({
    hero: Object.freeze({
      title: 'Descubre qué está frenando la escalabilidad de tu plataforma',
      subtitle: 'Auditamos arquitectura, cloud, seguridad y entrega de software para convertir riesgos técnicos en un roadmap priorizado de 90 días.',
      primaryCta: 'Agendar llamada de 30 minutos',
      secondaryCta: 'Ver entregables',
      reassurance: 'Sin compromiso. No necesitas preparar documentación técnica para la primera llamada.',
    }),
    idealClientScenarios: Object.freeze([
      'La plataforma ha crecido sin una revisión arquitectónica integral.',
      'Los despliegues e incidentes están frenando al equipo.',
      'El gasto cloud crece más rápido que el negocio.',
      'Existen dudas sobre escalabilidad, seguridad o deuda técnica.',
      'Se necesita validar la tecnología antes de una inversión, migración o nueva etapa de crecimiento.',
      'La empresa no cuenta con liderazgo técnico senior de tiempo completo.',
    ]),
    scope: Object.freeze([
      'Revisión de arquitectura.',
      'Revisión de infraestructura cloud.',
      'Evaluación de seguridad técnica.',
      'Revisión de pipelines y procesos de entrega.',
      'Análisis de riesgos, deuda técnica y escalabilidad.',
      'Entrevistas con responsables de tecnología, producto y negocio.',
    ]),
    duration: 'Duración típica: entre 2 y 4 semanas, dependiendo del alcance y la complejidad de la plataforma.',
    deliverables: Object.freeze([
      'Resumen ejecutivo.',
      'Scorecard técnico.',
      'Inventario de hallazgos.',
      'Matriz de impacto y esfuerzo.',
      'Riesgos priorizados.',
      'Recomendaciones técnicas.',
      'Roadmap de 90 días.',
      'Sesión de presentación de resultados.',
    ]),
  }),
});
