// @ts-check
export const siteConfig = Object.freeze({
  brandName: 'Jato Labs',
  founderName: 'Miguel Jato',
  domain: 'https://jatolabs.tech',
  email: 'hola@jatolabs.tech',
  location: 'México / Remoto',
  linkedinUrl: 'https://www.linkedin.com/in/jatomx/',
  bookingUrl: '',
  bookingSubject: 'Llamada de 30 minutos para mi empresa',
  primaryCta: Object.freeze({ label: 'Agendar llamada de 30 minutos' }),
  navigation: Object.freeze([
    Object.freeze({ label: 'Servicios', href: '#servicios' }),
    Object.freeze({ label: 'Proceso', href: '#proceso' }),
    Object.freeze({ label: 'Entregables', href: '#reporte' }),
    Object.freeze({ label: 'Experiencia', href: '#experiencia' }),
    Object.freeze({ label: 'Preguntas frecuentes', href: '#preguntas-frecuentes' }),
    Object.freeze({ label: 'Contacto', href: '#contacto' }),
  ]),
  audit: Object.freeze({
    hero: Object.freeze({
      title: 'Descubre qué está frenando la escalabilidad de tu plataforma',
      subtitle: 'Auditamos arquitectura, cloud, seguridad y entrega de software para convertir riesgos técnicos en un roadmap priorizado de 90 días.',
      secondaryCta: 'Ver entregables',
      reassurance: 'Sin compromiso. No necesitas preparar documentación técnica para la primera llamada.',
    }),
    idealClientScenarios: Object.freeze([
      'La plataforma ha crecido sin una revisión arquitectónica integral.',
      'Los despliegues e incidentes están frenando al equipo.',
      'El gasto cloud crece más rápido que el negocio.',
      'Existen dudas sobre escalabilidad, seguridad o deuda técnica.',
      'Se necesita validar la tecnología antes de una inversión, migración o nueva etapa de crecimiento.',
      'La empresa no cuenta con liderazgo técnico senior de tiempo completo.',
    ]),
    scope: Object.freeze([
      'Revisión de arquitectura.', 'Revisión de infraestructura cloud.',
      'Evaluación de seguridad técnica.', 'Revisión de pipelines y procesos de entrega.',
      'Análisis de riesgos, deuda técnica y escalabilidad.',
      'Entrevistas con responsables de tecnología, producto y negocio.',
    ]),
    duration: 'Duración típica: entre 2 y 4 semanas, dependiendo del alcance y la complejidad de la plataforma.',
    deliverables: Object.freeze([
      'Resumen ejecutivo.', 'Scorecard técnico.', 'Inventario de hallazgos.',
      'Matriz de impacto y esfuerzo.', 'Riesgos priorizados.', 'Recomendaciones técnicas.',
      'Roadmap de 90 días.', 'Sesión de presentación de resultados.',
    ]),
    scorecard: Object.freeze([
      Object.freeze({ label: 'Arquitectura', score: '72 / 100', status: 'Medio' }),
      Object.freeze({ label: 'Cloud', score: '64 / 100', status: 'Medio' }),
      Object.freeze({ label: 'Seguridad', score: '48 / 100', status: 'Alto' }),
      Object.freeze({ label: 'DevOps', score: '81 / 100', status: 'Bajo' }),
      Object.freeze({ label: 'Datos e IA', score: '69 / 100', status: 'Medio' }),
    ]),
    findings: Object.freeze([
      Object.freeze({ title: 'Dependencia crítica sin estrategia de recuperación', area: 'Arquitectura', severity: 'Crítico', impact: 'Interrupción prolongada del servicio', effort: 'Alto', recommendation: 'Definir redundancia, respaldos y un plan de recuperación probado.' }),
      Object.freeze({ title: 'Crecimiento de costos cloud sin asignación por servicio', area: 'Cloud', severity: 'Alto', impact: 'Decisiones de costo sin trazabilidad', effort: 'Medio', recommendation: 'Etiquetar recursos y establecer presupuestos por servicio.' }),
      Object.freeze({ title: 'Pipeline de despliegue con validaciones manuales', area: 'DevOps', severity: 'Medio', impact: 'Entregas lentas y propensas a error', effort: 'Bajo', recommendation: 'Automatizar validaciones críticas y criterios de promoción.' }),
      Object.freeze({ title: 'Secretos almacenados fuera de un gestor centralizado', area: 'Seguridad', severity: 'Alto', impact: 'Mayor exposición de credenciales', effort: 'Medio', recommendation: 'Migrar secretos y rotación a un gestor con acceso auditado.' }),
    ]),
    matrix: Object.freeze([
      Object.freeze({ quadrant: 'Alto impacto / bajo esfuerzo', initiative: 'Automatizar validaciones del pipeline' }),
      Object.freeze({ quadrant: 'Alto impacto / alto esfuerzo', initiative: 'Diseñar recuperación de la dependencia crítica' }),
      Object.freeze({ quadrant: 'Bajo impacto / bajo esfuerzo', initiative: 'Normalizar etiquetas de recursos cloud' }),
      Object.freeze({ quadrant: 'Bajo impacto / alto esfuerzo', initiative: 'Reorganizar ambientes no críticos' }),
    ]),
    roadmap: Object.freeze([
      Object.freeze({ period: '0–30 días', items: Object.freeze(['Contener riesgos críticos', 'Definir responsables y métricas']) }),
      Object.freeze({ period: '31–60 días', items: Object.freeze(['Automatizar controles prioritarios', 'Implementar trazabilidad de costos']) }),
      Object.freeze({ period: '61–90 días', items: Object.freeze(['Probar recuperación y continuidad', 'Revisar avances y ajustar el roadmap']) }),
    ]),
    process: Object.freeze([
      Object.freeze({ title: 'Descubrimiento', description: 'Objetivos, contexto de negocio y riesgos percibidos.', outcome: 'ALINEAR' }),
      Object.freeze({ title: 'Revisión basada en evidencia', description: 'Arquitectura, repositorios, cloud, procesos y entrevistas.', outcome: 'OBSERVAR' }),
      Object.freeze({ title: 'Priorización', description: 'Hallazgos ordenados por impacto, urgencia y esfuerzo.', outcome: 'DECIDIR' }),
      Object.freeze({ title: 'Sesión ejecutiva', description: 'Resultados, decisiones y ruta de acción con tu equipo.', outcome: 'ACTUAR' }),
    ]),
  }),
  serviceModes: Object.freeze([
    Object.freeze({ title: 'Diagnóstico técnico ejecutivo', description: 'Evaluación de alto nivel para identificar riesgos, bloqueos y oportunidades prioritarias.', items: Object.freeze(['Arquitectura general.', 'Cloud y costos.', 'Seguridad.', 'Flujo de entrega.', 'Recomendaciones ejecutivas.', 'Roadmap inicial.']), cta: 'Solicitar diagnóstico' }),
    Object.freeze({ title: 'Auditoría técnica especializada', description: 'Análisis profundo de un área crítica de la plataforma.', items: Object.freeze(['Arquitectura y escalabilidad.', 'Cloud y FinOps.', 'Seguridad y supply chain.', 'DevOps y confiabilidad.', 'Datos e inteligencia artificial.']), cta: 'Solicitar auditoría especializada' }),
  ]),
  expectedOutcomes: Object.freeze([
    'Identificación de riesgos críticos.', 'Priorización por impacto y esfuerzo.',
    'Reducción de incertidumbre técnica.', 'Visibilidad sobre deuda técnica.',
    'Detección de costos e ineficiencias.', 'Roadmap alineado con objetivos de negocio.',
    'Mejor base para decisiones de inversión, migración o crecimiento.',
  ]),
  technicalProfile: Object.freeze({
    role: 'Technology Executive · CTO · Cloud Architect',
    introduction: 'Miguel Jato combina más de 20 años de experiencia tecnológica con una trayectoria liderando equipos de ingeniería, construyendo plataformas digitales y llevando sistemas críticos desde la arquitectura hasta producción.',
    perspective: 'Su experiencia conecta profundidad técnica y dirección ejecutiva: entiende las decisiones de arquitectura, cloud y seguridad, pero también su impacto en costos, velocidad de entrega, riesgo operativo y crecimiento del negocio.',
    highlights: Object.freeze([
      Object.freeze({ value: '20+', label: 'años de experiencia en tecnología' }),
      Object.freeze({ value: 'AWS + GCP', label: 'arquitectura y operación multi-cloud' }),
      Object.freeze({ value: 'CTO', label: 'liderazgo técnico y de ingeniería' }),
    ]),
    expertise: Object.freeze([
      'Arquitectura cloud', 'Plataformas SaaS', 'Modernización tecnológica',
      'Sistemas de misión crítica', 'Liderazgo de ingeniería',
      'Migraciones e integraciones', 'Seguridad y confiabilidad',
    ]),
    credential: Object.freeze({
      name: 'AWS Certified Solutions Architect – Associate',
      issuer: 'Amazon Web Services',
      validity: 'Vigente hasta abril de 2027',
    }),
    linkedinCta: 'Conocer la trayectoria completa en LinkedIn',
  }),
  faqs: Object.freeze([
    Object.freeze({ question: '¿Necesito compartir el código fuente?', answer: 'No necesariamente desde el inicio. El acceso se acuerda según el alcance; algunas revisiones pueden comenzar con arquitectura, configuración, procesos y entrevistas. Cuando revisar código aporta evidencia relevante, se solicita acceso limitado y explícito.' }),
    Object.freeze({ question: '¿Cómo se protege la información de mi empresa?', answer: 'Antes de compartir información se acuerdan el alcance, los accesos y las medidas de confidencialidad aplicables. Se procura usar accesos mínimos y temporales. Los requisitos contractuales específicos se confirman durante la conversación inicial.' }),
    Object.freeze({ question: '¿La auditoría incluye pruebas de penetración?', answer: 'No se asumen como parte del alcance estándar. La auditoría revisa controles y riesgos técnicos; si se requieren pruebas de penetración, se valida por separado el alcance y la forma adecuada de realizarlas.' }),
    Object.freeze({ question: '¿Trabajan con AWS y Google Cloud?', answer: 'Sí. La experiencia publicada incluye plataformas operadas sobre AWS y Google Cloud. El alcance concreto depende de la arquitectura y los servicios utilizados por tu empresa.' }),
    Object.freeze({ question: '¿Cuánto tiempo debe dedicar mi equipo?', answer: 'Se busca concentrar la participación en entrevistas, habilitación de accesos y validación de hallazgos. La dedicación exacta depende del alcance, la documentación disponible y la complejidad de la plataforma.' }),
    Object.freeze({ question: '¿Pueden ayudar a implementar las recomendaciones?', answer: 'La posible participación posterior se evalúa según las prioridades, capacidades del equipo y disponibilidad. No forma parte automáticamente de la auditoría y se acuerda por separado.' }),
    Object.freeze({ question: '¿La auditoría sirve para procesos de due diligence?', answer: 'Puede aportar evidencia técnica para decisiones de inversión o crecimiento. Los objetivos, profundidad y formato necesarios para un proceso de due diligence deben acordarse específicamente.' }),
    Object.freeze({ question: '¿Cuánto dura la auditoría?', answer: 'La duración típica es de entre 2 y 4 semanas, dependiendo del alcance y la complejidad de la plataforma.' }),
    Object.freeze({ question: '¿Qué información necesito preparar?', answer: 'No necesitas preparar documentación técnica para la primera llamada. Después se define una lista acotada de arquitectura, accesos, métricas y personas relevantes según el alcance acordado.' }),
    Object.freeze({ question: '¿Pueden trabajar con mi equipo o proveedor actual?', answer: 'Sí, la revisión está planteada como un proceso colaborativo. La forma de coordinación, responsabilidades y acceso se acuerda con las partes involucradas antes de iniciar.' }),
  ]),
  footer: Object.freeze({
    navigation: Object.freeze([
      Object.freeze({ label: 'Servicios', href: '#servicios' }),
      Object.freeze({ label: 'Proceso', href: '#proceso' }),
      Object.freeze({ label: 'Entregables', href: '#reporte' }),
      Object.freeze({ label: 'Preguntas frecuentes', href: '#preguntas-frecuentes' }),
      Object.freeze({ label: 'Contacto', href: '#contacto' }),
    ]),
    legal: Object.freeze([]),
  }),
  seo: Object.freeze({ title: 'Jato Labs | Auditoría técnica especializada', description: 'Jato Labs audita arquitectura, cloud, seguridad y operaciones técnicas para convertir riesgos en decisiones y un roadmap priorizado.' }),
});
